### ISSUE TITLE
Compile instructions need libnewlib-arm-none-eabi

### ISSUE THREAD

**Issue by andy-preston** [koendv/blackmagic-bluepill#1]
During compilation, I had a repeated error message:
`/usr/lib/gcc/arm-none-eabi/6.3.1/include/stdint.h:9:26: fatal error: stdint.h: No such file or directory`

I eventually fixed this with `sudo apt-get install libnewlib-arm-none-eabi` which pulled in the `libnewlib-dev` dependency and fixed this problem. It'd be good if your compilation instructions also listed this dependency.

**Comment by koendv** [comment]
OK. I've added this to the compilation instructions. Thanks.
