### ISSUE TITLE
Serial port TX not working

### ISSUE THREAD

**Issue by Thi3rryzz** [koendv/blackmagic-bluepill#4]
Hi,
First off, great job on creating this port!
With the latest release V1.8-1, The optional serial port TX doesn't transmit any data, receiving still works fine.
I'm currently using release 1.6.1-3, with this one, the serial port does work like a charm.

Thanks!

**Comment by koendv** [comment]
On Mon, 26 Sep 2022 03:06:37 -0700
Thi3rryzz ***@***.***> wrote:

> Hi,
> First off, great job on creating this port!
> With the latest release V1.8-1, The optional serial port TX doesn't
> transmit any data, receiving still works fine. I'm currently using
> release 1.6.1-3, with this one, the serial port does work like a
> charm.
> 
> Thanks!
> 

Thank you. I think this is because the bmp is compiled with RTT
support, and characters typed in then go to the RTT session.

koen

**Comment by koendv** [comment]
Can you try the latest and greatest?
Expected behavior:
- if rtt is enabled "mon rtt ena" then characters typed in go to rtt
- if rtt is not enabled, characters typed in go to serial port

**Comment by Thi3rryzz** [comment]
Works like a charm!
Thanks!
